Config = Config or {}

Config.UsingDefaultQBApartments = false
Config.OnlyShowOnDuty = true
Config.UseCQCMugshot = false

-- Front, Back Side. Use 4 for both sides, we recommend leaving at 1 for default.
Config.MugPhotos = 1

-- Images for mug shots will be uploaded here. Add a Discord webhook.
Config.Webhook = ''

-- Clock-in notifications for duty. Add a Discord webhook.
-- Command /mdtleaderboard, will display top players per clock-in hours.
Config.ClockinWebhook = ''

-- If set to true = Fine gets automatically removed from bank automatically charging the player.
-- If set to false = The fine gets sent as an Invoice to their phone and it us to the player to pay for it, can remain unpaid and ignored.
Config.BillVariation = true

-- Set up your inventory to automatically retrieve images when a weapon is registered at a weapon shop or self-registered.
-- If you're utilizing lj-inventory's latest version from GitHub, no further modifications are necessary.
-- However, if you're using a different inventory system, please refer to the "Inventory Edit | Automatic Add Weapons with images" section in ps-mdt's README.
Config.InventoryForWeaponsImages = "lj-inventory"

-- "LegacyFuel", "lj-fuel", "ps-fuel"
Config.Fuel = "ps-fuel"

-- Google Docs Link
Config.sopLink = {
    ['police'] = 'https://docs.google.com/document/d/e/2PACX-1vRsIDmPavPGGyQOeD-w3Ki4Cz4fPOCglWPI5n0qpWldN4KLYe1aWeG-t_40CzfL5UBDaTV-kjZLuaZJ/pub',
    ['ambulance'] = '',
    -- ['bcso'] = '',
    -- ['doj'] = '',
    -- ['sast'] = '',
    -- ['sasp'] = '',
    -- ['doc'] = '',
    -- ['lssd'] = '',
    -- ['sapr'] = '',
}

-- Google Docs Link
Config.RosterLink = {
    ['police'] = 'https://docs.google.com/spreadsheets/d/e/2PACX-1vRc1NLWmDshL3OCbWKl2kvKyOuA7M-mly6qw-1yOVZsC_rBGZV_AodWNnO9Hf2iTqj72XuVzrG9LPyi/pubhtml',
    -- ['ambulance'] = '',
    -- ['bcso'] = '',
    -- ['doj'] = '',
    -- ['sast'] = '',
    -- ['sasp'] = '',
    -- ['doc'] = '',
    -- ['lssd'] = '',
    -- ['sapr'] = '',
}

Config.PoliceJobs = {
    ['police'] = true,
    -- ['lspd'] = true,
    -- ['bcso'] = true,
    -- ['sast'] = true,
    -- ['sasp'] = true,
    -- ['doc'] = true,
    -- ['lssd'] = true,
    -- ['sapr'] = true,
    -- ['pa'] = true
}

Config.AmbulanceJobs = {
    ['ambulance'] = true,
    -- ['doctor'] = true
}

Config.DojJobs = {
    -- ['lawyer'] = true,
    ['judge'] = true,
}

-- This is a workaround solution because the qb-menu present in qb-policejob fills in an impound location and sends it to the event.
-- If the impound locations are modified in qb-policejob, the changes must also be implemented here to ensure consistency.

Config.ImpoundLocations = {
    [1] = vector4(436.68, -1007.42, 27.32, 180.0),
    [2] = vector4(-436.14, 5982.63, 31.34, 136.0),
}

-- Support for Wraith ARS 2X.

Config.UseWolfknightRadar = true
Config.WolfknightNotifyTime = 5000 -- How long the notification displays for in milliseconds (30000 = 30 seconds)

-- IMPORTANT: To avoid making excessive database queries, modify this config to true 'CONFIG.use_sonorancad = true' setting in the configuration file located at 'wk_wars2x/config.lua'.
-- Enabling this setting will limit plate checks to only those vehicles that have been used by a player.

Config.LogPerms = {
	['ambulance'] = {
		[4] = true,
	},
	['police'] = {
		[4] = true,
	},
    -- ['bcso'] = {
	-- 	[4] = true,
	-- },
    -- ['sast'] = {
	-- 	[4] = true,
	-- },
    -- ['sasp'] = {
	-- 	[4] = true,
	-- },
    -- ['sapr'] = {
	-- 	[4] = true,
	-- },
    -- ['doc'] = {
	-- 	[4] = true,
	-- },
    -- ['lssd'] = {
	-- 	[4] = true,
	-- },
}

Config.PenalCodeTitles = {
    [1] = 'ASSAULT/MURDER',
    [2] = 'THEFT / BURGLARY',
    [3] = 'DRUGS',
    [4] = 'PROPERTY DAMAGE / ENVIRONMENT',
    [5] = 'WEAPONS',
    [6] = 'PUBLIC ORDER AND CUSTODY',
    [7] = 'OBSTRUCT JUSTICE / CORRUPTION',
    [8] = 'FIREARMS',
    [9] = 'TRAFFIC - GENERAL',
    [10] = 'TRAFFIC - LICENSING / DEFECTS',
    [11] = 'TRAFFIC - LIGHTS / MARKINGS',
    [12] = 'TRAFFIC - VEHICLE OPERATION',
    [13] = 'TRAFFIC - SPEEDING',
    [14] = 'TRAFFIC - DRINK / DRUG DRIVING',
}

Config.PenalCode = {
    -- Assault / Murder
    [1] = {
        [1] = {title = 'Murder', class = 'Strictly Indictable', id = 'S. 18 C.A.', months = 50, fine = 80000, color = 'red', description = 'Section 18 Crimes Act (NSW) - Where an intentional voluntary act of the accused causes the death of the deceased'},
        [2] = {title = 'Murder emergency services worker', class = 'Strictly Indictable', id = 'S. 18 C.A.', months = 60, fine = 90000, color = 'red', description = 'Section 18 Crimes Act (NSW) Where an intentional voluntary act of the accused causes the death of the an emergency services worker'},
        [3] = {title = 'Attempted Murder', class = 'Strictly Indictable', id = 'S. 27 C.A.', months = 40, fine = 70000, color = 'red', description = 'Section 27 Crimes Act (NSW) - An attempted intentional voluntary act to cause the death of a person'},
        [4] = {title = 'Att. Murder emergency services worker', class = 'Strictly Indictable', id = 'S. 27 C.A.', months = 50, fine = 80000, color = 'red', description = 'Section 27 Crimes Act (NSW) - An attempted intentional voluntary act to cause the death of a person an emergency services worker'},
        [5] = {title = 'Manslaughter', class = 'Strictly Indictable', id = 'S. 18 C.A.', months = 30, fine = 30000, color = 'red', description = 'Section 18 Crimes Act (NSW) - A reckless act that causes the death of a person'},
        [6] = {title = 'Conspiring to Commit Murder', class = 'Strictly Indictable', id = 'S. 26 C.A.', months = 30, fine = 50000, color = 'red' , description = 'Section 26 Crimes Act (NSW) - Entering into an agreement to kill another person'},
        [7] = {title = 'Assault Causing Death', class = 'Strictly Indictable', id = 'S. 25A C.A.', months = 30, fine = 50000, color = 'red' , description = 'Section 25A Crimes Act (NSW) - Intentionally and unlawully assaulting or hitting another person causing their death '},
        [8] = {title = 'Intentional Wounding or grevious bodily harm', class = 'Indictable', id = 'S. 33 C.A.', months = 30, fine = 5000, color = 'red', description = 'Section 33 Crimes Act (NSW) - An attempted intentional voluntary act to cause the death of a person'},
        [9] = {title = 'Reckless grevious bodily harm or wounding', class = 'Indictable', id = 'S. 35 C.A.', months = 30, fine = 50000, color = 'orange', description = 'Section 35 Crimes Act (NSW) - Grevious bodily harm is defined as very serious harm, incuding permanent or serious disfigurement, destruction of a foetus, and any grevious bodily disease. Wounding is an injury involving the breaking or cutting o the skin.'},
        [10] = {title = 'Spiking Drink or Food', class = 'Indictable', id = 'S. 38A C.A.', months = 20, fine = 10000, color = 'orange', description = 'Section 38A Crimes Act (NSW) - Causing another person to consume drink or food containing an intoxicating substance that they are not aware of and intends that person to be harmed. Harm includes an impairment of the senses or understanding of a person that the person might reasonably be expected to object to in the circumstances.'},
        [11] = {title = 'Assault occassioning actual bodily harm', class = 'Indictable', id = 'S. 59 C.A.', months = 20, fine = 10000, color = 'orange'},
        [12] = {title = 'Assault during public disorder', class = 'Indictable', id = 'S. 59A C.A.', months = 20, fine = 10000, color = 'orange', description = 'Section 59A Crimes Act (NSW) - Public disorder means a riot or other civil disturbance that gives rise to a serious risk to public safety, whether at a single location or resulting from a series of incidents in the same or different locations, and includes a riot or other civil disturbance at the following'},
        [13] = {title = 'Assault police in execution of duty', class = 'Indictable', id = 'S. 60(1) C.A.', months = 20, fine = 10000, color = 'orange', description = 'Section 60(1) Crimes Act (NSW) -  A person who assaults, throws a missile at, stalks, harasses or intimidates a police officer while in the execution of the officers duty, although no actual bodily harm is occasioned to the officer, is guilty of an offense'},
        [14] = {title = 'Throw missile at Police in exec. of duty', class = 'Indictable', id = 'S. 60(1) C.A.', months = 15, fine = 10000, color = 'orange', description = 'Section 60(1) Crimes Act (NSW) -  A person who assaults, throws a missile at, stalks, harasses or intimidates a police officer while in the execution of the officers duty, although no actual bodily harm is occasioned to the officer, is guilty of an offense'},
        [15] = {title = 'Stalk/Harrass/Intimidate Police in exec. of duty', class = 'Indictable', id = 'S. 60(1) C.A.', months = 20, fine = 10000, color = 'orange', description = 'Section 60(1) Crimes Act (NSW) -  A person who assaults, throws a missile at, stalks, harasses or intimidates a police officer while in the execution of the officers duty, although no actual bodily harm is occasioned to the officer, is guilty of an offense'},
        [16] = {title = 'Assault police causing bodily harm', class = 'Indictable', id = 'S. 60(2) C.A.', months = 20, fine = 15000, color = 'orange', description = 'Section 60(2) Crimes Act (NSW) - A person who assaults a police officer while in the execution of the officers duty, and by the assault occasions actual bodily harm, is guilty of an offense'},
        [17] = {title = 'Kidnapping', class = 'Strictly Indictable', id = 'S. 86 C.A.', months = 30, fine = 50000, color = 'red', description = 'Section 86 Crimes Act (NSW) - Taking or detaning a person without their consent with the intention of holding the person to ransom, or committing a serious indictable offense, or obtaining any other advantage'},
        [18] = {title = 'Blackmail', class = 'Indictable', id = 'S. 249K C.A.', months = 10, fine = 10000, color = 'orange', description = 'Section 249K Crimes Act (NSW) - A person who makes any unwarranted demand with menaces, with the intention of obtaining a gain or causing a loss, or with the intention of influencing the exercise of public duty. Menaces include any express, implied, or general threat of any action that is detrimental or unpleasant'},
        [19] = {title = 'Common Assault', class = 'Indictable', id = 'S. 61 C.A.', months = 10, fine = 10000, color = 'orange', description = 'Section 61 Crimes Act (NSW) - Whosoever assaults any person, although not occasioning actual bodily harm, shall be guilty of an offence'},
        [20] = {title = 'Stalking', class = 'Indictable', id = 'S13 C(DPV) Act', months = 20, fine = 10000, color = 'orange', description = 'Section 13 Crimes (Domestic and Personal Violence) Act 2007(NSW) - the following of a person about or the watching or frequenting of the vicinity of, or an approach to a person’s place of residence, business or work or any place that a person frequents for the purposes of any social or leisure activity. Stalking involves a persistent course of conduct or actions by a person which are intended to maintain contact with or exercise power and control over another person. These actions cause distress, loss of control, fear or harassment to another person and occur more than once.'},
        [21] = {title = 'Intimidation', class = 'Indictable', id = 'S. 7 C(DPV) Act', months = 20, fine = 10000, color = 'orange', description = 'Section 13 Crimes (Domestic and Personal Violence) Act 2007 (NSW) - A person who stalks or intimidates another person with the intention of causing the other person to fear physical or mental harm is guilty of an offence.'},

    },
     -- Theft / Burglary
    [2] = {

        [1] = {title = 'Robbery', class = 'Indictable', id = 'S. 94 C.A.', months = 30, fine = 40000, color = 'orange', description = 'Section 94 Crimes Act (NSW) - Robbery is the act of unlawfully taking property from a person by force or the threat of force or by putting the victim in fear.'},
        [2] = {title = 'Attempted Robbery', class = 'Indictable', id = 'S. 94 C.A.', months = 30, fine = 30000, color = 'orange', description = 'Section 94 Crimes Act (NSW) - Robbery is the act of unlawfully taking property from a person by force or the threat of force or by putting the victim in fear.'},
        [3] = {title = 'Aggravated Robbery', class = 'Indictable', id = 'S. 95 C.A.', months = 40, fine = 50000, color = 'orange', description = 'Section 95 Crimes Act (NSW) - Robbery causing a person to suffer physical injury, bodily harm, or depriving a person of their liberty whilst doing so.'},
        [4] = {title = 'Burglary (Break and Enter)', class = 'Indictable', id = 'S. 109 C.A.', months = 20, fine = 10000, color = 'orange', description = 'Section 109 Crimes Act (NSW) - Breaking and entering a dwelling-house or other building and committing any serious indictable offence (i.e. breaking into a house and stealing a TV)'},
        [5] = {title = 'Armed w/ intent to commit ind. offence', class = 'Indictable', id = 'S. 114 C.A.', months = 10, fine = 10000, color = 'orange', description = 'Section 114 Crimes Act (NSW) - Armed with a weapon or instrument with the intent of committing an indictable offense (i.e. Using a pistol to rob a person)'},
        [6] = {title = 'Theft', class = 'Indictable', id = 'S. 117 C.A.', months = 10, fine = 10000, color = 'orange', description = 'Section 117 Crimes Act (NSW) - Intentionally, dishonestly, taking property belonging to another without consent with the intent to permanently deprive that person of that property. Having a claim of right is a defence to the charge which is where you genuinely believed you were legally entitled to the property'},
        [7] = {title = 'Stealing aircraft', class = 'Indictable', id = 'S. 154B C.A.', months = 30, fine = 30000, color = 'orange', description = 'Section 154B Crimes Act (NSW) - Directly or indirectly taking or exercising control of an aircraft without lawful excuse'},
        [8] = {title = 'Stealing firearms', class = 'Indictable', id = 'S. 154D C.A.', months = 30, fine = 30000, color = 'orange', description = 'Section 154D Crimes Act (NSW) - Taking and carrying away of a firearm without the owners permission, and without any intention of returning it.'},
        [9] = {title = 'Stealing motor vehicle, vessel or trailer (NPC)', class = 'Summary', id = 'S. 154F C.A.', months = 15, fine = 1500, color = 'green', description = 'Section 154F Crimes Act NSW - Stealing a vehicle belonging to an NPC'},
        [10] = {title = 'Stealing motor vehicle, vessel or trailer (Player)', class = 'Indictable', id = 'S. 154F C.A.', months = 15, fine = 8000, color = 'orange', description = 'Section 154F Crimes Act NSW - Stealing a vehicle belonging to a player'},
        [11] = {title = 'Fraud', class = 'Indictable', id = 'S. 192E C.A.', months = 15, fine = 8000, color = 'orange', description = 'Section 192E Crimes Act (NSW) - Obtaining property or financial advantage by deception'},
        [12] = {title = 'Possess ID w/ intent to commit ind. offence', class = 'Indictable', id = 'S. 192K C.A.', months = 15, fine = 5000, color = 'orange', description = 'Section 192K Crimes Act (NSW) - A person who possesses identification information with the intention of committing, or of facilitating the commission of, an indictable offence is guilty of an offence'},
        [13] = {title = 'Possess equip. to make false ID', class = 'Indictable', id = 'S. 192L C.A.', months = 15, fine = 5000, color = 'orange', description = 'Section 192L Crimes Act (NSW) - A person who possesses any equipment, material or other thing that is capable of being used to make a document or other thing containing identification information, and intends that the document or other thing made will be used to commit, or to facilitate the commission of, an indictable offence'},
        [14] = {title = 'Money Laundering', class = 'Indictable', id = 'S. 193B C.A.', months = 25, fine = 25000, color = 'orange', description = 'Section 193B Crimes Act (NSW) - A person who deals with proceeds of crime, knowing that it is proceeds of crime, and intending to conceal that it is proceeds of crime, is guilty of an offence'},
        [15] = {title = 'Deal w/ suspected proceeds of crime (<100k)', class = 'Summary', id = 'S. 193C (2) C.A.', months = 10, fine = 15000, color = 'green', description = 'Section 193C(2) Crimes Act (NSW) - A person deals with property and there are reasonable grounds to suspect the property is proceeds of crime. Proceeds of crime includes money/property derived from crime (i.e. drug trafficking). If there are reasonable grounds to suspect that it is proceeds of crime, it is an offence to deal with it. Ignorance is no excuse'},
        [16] = {title = 'Deal w/ suspected proceeds of crime (>100k)', class = 'Indictable', id = 'S. 193C (1) C.A.', months = 25, fine = 20000, color = 'orange', description = 'Section 193C(1) Crimes Act (NSW) - A person deals with property and there are reasonable grounds to suspect the property is proceeds of crime. Proceeds of crime includes money/property derived from crime (i.e. drug trafficking). If there are reasonable grounds to suspect that it is proceeds of crime, it is an offence to deal with it. Ignorance is no excuse'},
        [17] = {title = 'Corrupting Betting Outcome of Event', class = 'Summary', id = 'S. 193H C.A.', months = 15, fine = 15000, color = 'green', description = 'Section 193H Crimes Act (NSW) - Knowingly or recklessly engaging in conduct that corrupted a betting outcome to cause financial advantage or disadvantage'},
        [18] = {title = 'Using false document', class = 'Indictable', id = 'S. 254 C.A.', months = 10, fine = 10000, color = 'orange', description = 'Section 254 Crimes Act (NSW) - A person who uses a false document, knowing that it is false, with the intention of inducing some person to accept it as genuine, and because of its being accepted as genuine, obtaining any property belonging to another or, obtaining any financial advantage or causing any financial disadvantage, or influencing the exercise of a public duty'},
        [19] = {title = 'Possession of false document', class = 'Indictable', id = 'S. 255 C.A.', months = 10, fine = 10000, color = 'orange', description = 'Section 255 Crimes Act (NSW) - A person who possesses a false document, knowing that it is false, with the intention of inducing some person to accept it as genuine, and because of its being accepted as genuine, obtaining any property belonging to another or, obtaining any financial advantage or causing any financial disadvantage, or influencing the exercise of a public duty'},
        [20] = {title = 'Computer Hacking', class = 'Indictable', id = 'S. 308C C.A.', months = 15, fine = 10000, color = 'orange', description = 'Section 308C Crimes Act (NSW) - A person who causes any unauthorised computer function, knowing it is unauthorised, with the intention of committing a serious indictable offfence or facilitating the commission of a serious indicatable offence'},
        [21] = {title = 'Posession of data for computer offence', class = 'Indictable', id = 'S. 308F C.A.', months = 15, fine = 10000, color = 'orange', description = 'Section 308F Crimes Act (NSW) - Possessing or being in control of data with the intention of committing or facilitating a serious computer offence (i.e. possessing a Trojan USB stick)'},
        [22] = {title = 'Unauthorised access to restricted data', class = 'Summary', id = 'S. 308H C.A.', months = 15, fine = 5000, color = 'green', description = 'Section 308H (NSW) - A person who intentionally causes any unauthorised access to, or modification of restricted data held in a computer, knowing that access or modification is unauthorised. Restricted data means data held in a computer, being data to which access is restricted by an access control system associated with a function of the computer.'},
        [23] = {title = 'Unauthorised Entry to Vehicle or Boat', class = 'Summary', id = 'S. 6A S.O.A', months = 0, fine = 2500, color = 'green', description = 'Section 6A Summary Offences Act (NSW) - A person must not, without reasonable excuse (proof of which lies on the person), enter any vehicle or boat in a public place without the consent of the owner or lawful occupier of the vehicle or boat.'},

    },

        --  Drugs
    [3] = {
        [1] = {title = 'Possess prohibited drug', class = 'Summary', id = 'S10 D.M.T.A', months = 15, fine = 7500, color = 'green', description = 'Section 10 Drugs Misuse and Trafficking Act (NSW) - Possession of less than 50 units of a prohibited drug'},
        [2] = {title = 'Possess equip. for prohib. drug use', class = 'Summary', id = 'S. 11 D.M.T.A', months = 10, fine = 2000, color = 'green', description = 'Section 11 Drugs Misuse and Trafficking Act (NSW) - Possessing any item for administration of a prohibited drug (i.e. syringe, bongs etc)'},
        [3] = {title = 'Forging prescriptions', class = 'Summary', id = 'S15 D.M.T.A', months = 25, fine = 7500, color = 'green'},
        [4] = {title = 'Obtain prescription by false representation', class = 'Summary', id = 'S15 D.M.T.A', months = 25, fine = 7500, color = 'green'},
        [5] = {title = 'Cultivate prohibited plant', class = 'Indictable', id = 'S23 D.M.T.A', months = 30, fine = 15000, color = 'orange'},
        [6] = {title = 'Manufacture/produce prohibited drugs', class = 'Indictable', id = 'S24 D.M.T.A', months = 30, fine = 15000, color = 'orange', description = 'Section 24 Drugs Misuse and Trafficking Act (NSW) - A person who manufactures or produces, or who knowingly takes part in the manufacture or production of, a prohibited drug is guilty of an offence'},
        [7] = {title = 'Possess precursors for production of prohibited drugs', class = 'Indictable', id = 'S24B D.M.T.A', months = 30, fine = 15000, color = 'orange', description = 'Section 24B Drugs Misuse and Trafficking Act (NSW) - Precursor means a substance that is a capable of being used to manufacture or produce a prohibited drug and specified in the regulations as a precursor. It is a defence to have a precursor for lawful activity or a reasonable excuse for possessing it'},
        [8] = {title = 'Possess prohibited drug (traffickable)', class = 'Indictable', id = 'S25 D.M.T.A', months = 25, fine = 15000, color = 'orange', description = 'Possessing 50-300 units'},
        [9] = {title = 'Supply prohibited drugs', class = 'Indictable', id = 'S25 D.M.T.A', months = 30, fine = 15000, color = 'orange'},
        [10] = {title = 'Supply prohibited drugs (Commercial)', class = 'Indictable', id = 'S25 D.M.T.A', months = 40, fine = 30000, color = 'orange', description = '300 units to 2000 units. Possessing commercial quantities is deemed for supply. Police do not have to see someone supplying commercial amounts to charge for supply, possession of commercial quantities is enough to prove supply. Supply includes sell and distribute, and also includes agreeing to supply, or offering to supply, or keeping or having in possession for supply, or sending, forwarding, delivering or receiving for supply, or authorising, directing, causing, suffering, permitting or attempting any of those acts or things.'},
        [11] = {title = 'Supply prohibited drugs (Large Commercial)', class = 'Strictly Indictable', id = 'S25 D.M.T.A', months = 50, fine = 50000, color = 'red', description = '2000 units or more. Possessing commercial quantities is deemed for supply. Police do not have to see someone supplying commercial amounts to charge for supply, possession of commercial quantities is enough to prove supply. Supply includes sell and distribute, and also includes agreeing to supply, or offering to supply, or keeping or having in possession for supply, or sending, forwarding, delivering or receiving for supply, or authorising, directing, causing, suffering, permitting or attempting any of those acts or things.'},
    },
        -- Property Damage / Environment
    [4] = {
        [1] = {title = 'Destroying or damaging property', class = 'Indictable', id = 'S. 195 C.A.', months = 10, fine = 10000, color = 'orange'},
        [2] = {title = 'Arson', class = 'Indictable', id = 'S. 195 C.A.', months = 20, fine = 10000, color = 'orange'},
        [3] = {title = 'Marking Premises or Property (Graffiti)', class = 'Summary', id = 'S. 4 G.C.A.', months = 0, fine = 5000, color = 'green', description = 'Section 4 Graffiti Control Act (NSW) - A person must not, without reasonable excuse (proof of which lies on the person), intentionally mark any premises or other property, unless the person has first obtained the consent of the owner, occupier, or person in charge of the premises'},
        [4] = {title = 'Poss. graffiti implement w/ intent to mark graffiti', class = 'Summary', id = 'S. 5 G.C.A.', months = 20, fine = 1000, color = 'green', description = 'Section 5 Graffiti Control Act (NSW) - A person must not have any graffiti implement in the persons possession with the intention that it be used to commit an offence. Graffiti implement means spraypaint, marker pen, or any implement designed or modified to produce a mark that is not readily removable by wiping or by use of water or detergent'},
        [5] = {title = 'Littering', class = 'Summary', id = 'S145 P.O.T.E.A', months = 0, fine = 1000, color = 'green'},
        [6] = {title = 'Aggravated Littering', class = 'Summary', id = 'S145A P.O.T.E.A', months = 0, fine = 2000, color = 'green', description = 'SECT 145A PROTECTION OF THE ENVIRONMENT OPERATIONS ACT (NSW) - Littering is aggravated when it caused or contributed to appreciable danger or harm to any persons, animals, premises or property, or was reasonably likely to cause or contribute to such danger or harm (whether or not any such danger or harm was actually caused)'},
        [7] = {title = 'Unlicensed Hunting', class = 'Summary', id = 'S16 G.F.A.C.A', months = 0, fine = 5000, color = 'green', description = 'SECT 16 GAME AND FERAL ANIMAL CONTROL ACT (NSW) - A person who hunts a game animal on any private land or public land is guilty of an offence unless the person is the holder of a game hunting licence.'},
        [8] = {title = 'Contravene Hunting Licence Conditions', class = 'Summary', id = 'S23 G.F.A.C.A', months = 0, fine = 5000, color = 'green'},
        [9] = {title = 'Harm protected species', class = 'Summary', id = 'S. 2.1 BDCA', months = 0, fine = 15000, color = 'green', description = 'Section 2.1 Biodiversity Conservation Act (NSW) - Harming or attempting to harm a protected animal or threatened species'},
        [10] = {title = 'Dealing in protected animals or plants', class = 'Summary', id = 'S. 2.5 BDCA', months = 0, fine = 25000, color = 'green', description = 'Section 2.1 Biodiversity Conservation Act (NSW) - Dealing or attempting to deal with protected animals, plants or threatened species.'},
        [11] = {title = 'Misconduct with regard to corpses', class = 'Indictable', id = 'S. 81C C.A.', months = 10, fine = 10000, color = 'orange', description = 'Section 81C Crimes Act (NSW) - Any person who indecently interferes with any dead human body, or improperly interferes with, or offers any indignity to, any dead human body or human remains (whether buried or not) shall be liable to imprisonment for 10 months '},

    },
    -- Weapons
    [5] = {
        [1] = {title = 'Possess explosives', class = 'Indictable', id = 'S. 93FA (1) C.A.', months = 20, fine = 20000, color = 'orange'},
        [2] = {title = 'Supply or make explosives', class = 'Indictable', id = 'S. 93FA(2) C.A.', months = 30, fine = 30000, color = 'orange'},
        [3] = {title = 'Possess dangerous article', class = 'Summary', id = 'S. 93FB C.A.', months = 15, fine = 15000, color = 'green', description = 'Section 93FB Crimes Act (NSW) - Any person who in a public place possess anything (not being a firearm) capable of discharging by any means any irritant matter in liquid, powder, gas or chemical form or any dense smoke, or any substance capable of causing bodily harm, or fuse capable of use with an explosive or a detonator, or a detonator, or a distress signal, or distress flare, that operates by emitting a bright light'},
        [4] = {title = 'Convey false info that person or property is in danger', class = 'Indictable', id = 'S. 93Q C.A.', months = 20, fine = 20000, color = 'orange', description = 'Section 93Q Crimes Act (NSW) - Example: Bomb threat - A person who conveys information  that the person knows to be false or misleading, and that is likely to make the person to whom the information is conveyed fear for the safety of a person or of property, or both is guilty of an offence'},
        [5] = {title = 'Leave or send article w/ intent to cause alarm', class = 'Indictable', id = 'S. 93R C.A.', months = 20, fine = 20000, color = 'orange', description = 'Section 93R Crimes Act (NSW) - Example: Leaving a fake bomb somewhere -  A person who leaves in any place, or sends by any means, a substance or article, and who intends to induce a false belief that the substance or article is likely to be a danger to the safety of a person or of property, or both, is guilty of an offence'},
        [6] = {title = 'Custody of knife in public place', class = 'Summary', id = 'S11C S.O.A', months = 0, fine = 5000, color = 'green', description = 'Section 11C Summary Offenses Act - A person must not, without reasonable excuse (proof of which lies on the person), have in his or her custody a knife in a public place or a school. Reasonable excuses include work, education, training, preparation of food, lawful entertainment or sport, exhibition of knives for retail or trade, wearing of an official uniform, genuine religious purposes. Self defence is NOT a reasonable excuse.'},
        [7] = {title = 'Possess Prohibited Weapon', class = 'Summary', id = 'S. 7 Weapon Prohibition Act', months = 0, fine = 5000, color = 'green', description = 'Anything contained in Schedule 1 of the Weapons Prohibition Act - Includes: Body armor, batons, tasers, handcuffs, tyre deflation devices (spike strips), pepper spray, swords'},



    },
    -- Public Order & Custody
    [6] = {
        [1] = {title = 'Riot', class = 'Indictable', id = 'S. 93B C.A.', months = 20, fine = 10000, color = 'orange', description = 'Section 93B Crimes Act (NSW) - Where 12 or more persons who are present together use or threaten unlawful violence for a common purpose and the conduct of them (taken together) is such as would cause a person of reasonable firmness present at the scene to fear for his or her personal safety, each of the persons using unlawful violence for the common purpose is guilty of riot'},
        [2] = {title = 'Affray', class = 'Indictable', id = 'S. 93C C.A.', months = 10, fine = 10000, color = 'orange', description = 'Section 93C Crimes Act (NSW) - A person who uses or threatens unlawful violence towards another and whose conduct is such as would cause a person of reasonable firmness present at the scene to fear for his or her personal safety is guilty of affray'},
        [3] = {title = 'Participation in criminal groups', class = 'Indictable', id = 'S. 93T C.A.', months = 20, fine = 10000, color = 'orange', description = 'Section 93T Crimes Act (NSW) - Criminal group means 3 or more people who have the objective to obtain material benefits from serious indictable offences or commit serious violent offences. A person who participates in a criminal group is guilty of an offence if the person knows or ought reasonably to know it is a criminal group and that their participation contributes to the occurence of any criminal activity'},
        [4] = {title = 'Conducting unlawful gambling operation', class = 'Summary', id = 'S. 93V C.A.', months = 10, fine = 10000, color = 'green'},
        [5] = {title = 'Threatening/inciting violence on grounds of predjudice', class = 'Indictable', id = 'S. 93Z C.A.', months = 30, fine = 30000, color = 'orange', description = 'Section 93Z Crimes Act (NSW) -  A person who, by a public act, intentionally or recklessly threatens or incites violence on the grounds of race, religion, sexual orientation, gender identity or intersex or HIV/AIDS status'},
        [6] = {title = 'Rescuing inmate from lawful custody', class = 'Indictable', id = 'S. 310B C.A.', months = 50, fine = 50000, color = 'orange'},
        [7] = {title = 'Aiding escape', class = 'Indictable', id = 'S. 310C C.A.', months = 30, fine = 30000, color = 'orange'},
        [8] = {title = 'Escape lawful custody', class = 'Indictable', id = 'S. 310D C.A.', months = 40, fine = 40000, color = 'orange'},
        [9] = {title = 'Harbouring escapee', class = 'Indictable', id = 'S. 310G C.A.', months = 20, fine = 20000, color = 'orange', description = 'Section 310G Crimes Act (NSW) - Any person who knowingly harbours, maintains or employs an escaped inmate is guilty of an offence'},
        [10] = {title = 'Offensive Conduct or Language', class = 'Summary', id = 'S. 4 S.O.A', months = 0, fine = 1500, color = 'green'},
        [11] = {title = 'Obstructing Traffic', class = 'Summary', id = 'S. 6 S.O.A', months = 0, fine = 1500, color = 'green'},
        [12] = {title = 'Obscene Exposure', class = 'Summary', id = 'S. 5 S.O.A', months = 0, fine = 1500, color = 'green'},
        [13] = {title = 'Trespassing', class = 'Summary', id = 'S. 4 Inclosed Land Act', months = 10, fine = 3500, color = 'green'},
        [14] = {title = 'Fail to comply with move on direction', class = 'Summary', id = 'S. 199 LEPRA', months = 15, fine = 5000, color = 'green'},
        [15] = {title = 'Fail to leave licensed premises', class = 'Summary', id = 'S. 77 Liquor Act', months = 0, fine = 2000, color = 'green'}


    },
    -- Obstruct Justice / Corruption
    [7] = {
        [1] = {title = 'Knowingly make false accusation', class = 'Indictable', id = 'S. 314 C.A.', months = 10, fine = 10000, color = 'orange'},
        [2] = {title = 'Threatening or intimidating victims or witnesses', class = 'Indictable', id = 'S. 315A C.A.', months = 15, fine = 15000, color = 'orange'},
        [3] = {title = 'Tampering with evidence', class = 'Indictable', id = 'S. 317 C.A.', months = 15, fine = 15000, color = 'orange'},
        [4] = {title = 'Pervert the course of justice', class = 'Indictable', id = 'S. 319 C.A.', months = 15, fine = 15000, color = 'orange'},
        [5] = {title = 'Perjury', class = 'Summary', id = 'S. 327 C.A.', months = 5, fine = 15000, color = 'green'},
        [6] = {title = 'Fail to disclose identity', class = 'Summary', id = 'S. 12 LEPRA', months = 0, fine = 5000, color = 'green'},
        [7] = {title = 'Provide false or misleading info about identity', class = 'Summary', id = 'S. 12 LEPRA', months = 0, fine = 5000, color = 'green'},
        [8] = {title = 'Failure to remove face covering', class = 'Summary', id = 'S. 19B LEPRA', months = 0, fine = 2000, color = 'green'},
        [9] = {title = 'Resist/Hinder Police', class = 'Summary', id = 'S. 39 LEPRA', months = 15, fine = 5000, color = 'green'},
        [10] = {title = 'Incite Person to Resist/Hinder Police', class = 'Summary', id = 'S. 39 LEPRA', months = 15, fine = 5000, color = 'green'},
        [11] = {title = 'Use/possess weapon to resist arrest etc', class = 'Indictable', id = 'S. 33B C.A.', months = 30, fine = 15000, color = 'orange'},
        [12] = {title = 'Bribery', class = 'Indictable', id = 'Common Law', months = 30, fine = 15000, color = 'orange'},
        [13] = {title = 'Fail to appear at court', class = 'Summary', id = 'S. 79 Bail Act', months = 30, fine = 15000, color = 'green'},
        [14] = {title = 'Contempt of court', class = 'Summary', id = 'S. 24 Local Court Act', months = 15, fine = 10000, color = 'green'},
        [15] = {title = 'Illegally record private conversation', class = 'Summary', id = 'S7 S.D.A.', months = 0, fine = 10000, color = 'green'},
        [16] = {title = 'Breach Apprehended Violence Order (AVO)', class = 'Indictable', id = 'S14 C(DPV) Act', months = 20, fine = 10000, color = 'orange'},
        [17] = {title = 'Contravene Community Corrections Order', class = 'Indictable', id = 'S107C C(A.O.S) Act', months = 30, fine = 10000, color = 'orange'},
        [18] = {title = 'Impersonation of Police Officers', class = 'Indictable', id = 'S. 546D C.A.', months = 30, fine = 10000, color = 'orange'},
        [19] = {title = 'Engage in legal practice by unqualified entity', class = 'Summary', id = 'S10 L.P.U.L', months = 10, fine = 10000, color = 'green'},
    },
    -- Firearms
    [8] = {
        [1] = {title = 'Discharge Firearm to Cause Grevious Bodily Harm', class = 'Indictable', id = 'S. 33A C.A.', months = 40, fine = 50000, color = 'orange'},
        [2] = {title = 'Possess Unregistered Firearm', class = 'Indictable', id = 'S. 36(1) F.A.', months = 20, fine = 17500, color = 'orange'},
        [3] = {title = 'Fail to ensure safe keeping of a firearm', class = 'Summary', id = 'S. 39 F.A.', months = 10, fine = 10000, color = 'green'},
        [4] = {title = 'Possession of Imitation Firearm', class = 'Indictable', id = 'S. 7 F.A.', months = 10, fine = 10000, color = 'orange'},
        [5] = {title = 'Possession/Use of Pistol', class = 'Indictable', id = 'S. 7 F.A.', months = 15, fine = 15000, color = 'orange'},
        [6] = {title = 'Possession/Use of Firearm (Non-pistol)', class = 'Summary', id = 'S. 7A F.A.', months = 5, fine = 10000, color = 'green'},
        [7] = {title = 'Possession/Use of Prohibited Firearm', class = 'Indictable', id = 'S. 7 F.A.', months = 30, fine = 25000, color = 'orange'},
        [8] = {title = 'Prohibted Person (FPO) Possess Firearm', class = 'Indictable', id = 'S. 74 F.A.', months = 20, fine = 20000, color = 'orange'},
        [9] = {title = 'Prohibted Person (FPO) Use Firearm', class = 'Indictable', id = 'S. 74 F.A.', months = 20, fine = 20000, color = 'orange'},
        [10] = {title = 'Prohibted Person (FPO) Aquire Firearm', class = 'Indictable', id = 'S. 74 F.A.', months = 20, fine = 20000, color = 'orange'},
        [11] = {title = 'Prohibted Person (FPO) Possess Firearm parts or ammo', class = 'Indictable', id = 'S. 74 F.A.', months = 20, fine = 20000, color = 'orange'},
        [12] = {title = 'Supply firearms, parts, ammo to prohibited person (FPO)', class = 'Indictable', id = 'S. 74 F.A.', months = 15, fine = 15000, color = 'orange'},
        [13] = {title = 'Possess loaded firearm in public place', class = 'Indictable', id = 'S. 93G(1)(a) C.A.', months = 15, fine = 3000, color = 'orange'},
        [14] = {title = 'Discharge firearm in or near a public place', class = 'Indictable', id = 'S. 93G(1)(b) C.A.', months = 15, fine = 3000, color = 'orange'},
        [15] = {title = 'Carry firearm in manner likely to injure', class = 'Indictable', id = 'S. 93G(1)(c) C.A.', months = 15, fine = 3000, color = 'orange'},
        [16] = {title = 'Manufacture firearms', class = 'Indictable', id = 'S. 50(1) F.A.', months = 30, fine = 30000, color = 'orange'},
        [17] = {title = 'Manufacture prohibited firearm', class = 'Indictable', id = 'S. 50(2) F.A.', months = 50, fine = 50000, color = 'orange'},
    },
    --Traffic General
    [9] = {
        [1] = {title = 'Engage in a Police Pursuit', class = 'Indictable', id = 'S. 51B C.A.', months = 40, fine = 50000, color = 'orange'},
        [2] = {title = 'Dangerous Driving Occassioning Death', class = 'Indictable', id = 'S. 52A (1) C.A.', months = 50, fine = 50000, color = 'orange'},
        [3] = {title = 'Dangerous Driving Occassioning Grevious Bodily Harm', class = 'Indictable', id = 'S. 52A (3) C.A.', months = 30, fine = 20000, color = 'orange'},
        [4] = {title = 'Fail to stop and assist after causing harm/death', class = 'Indictable', id = 'S. 52AB C.A.', months = 20, fine = 10000, color = 'orange'},
        [5] = {title = 'Cause injury by furious driving', class = 'Indictable', id = 'S. 53 C.A.', months = 20, fine = 10000, color = 'orange'},
        [6] = {title = 'Negligent Driving', class = 'Summary', id = 'S. 117 R.T.A.', months = 15, fine = 3000, color = 'green'},
        [7] = {title = 'Reckless Driving', class = 'Summary', id = 'S. 117 R.T.A.', months = 15, fine = 5000, color = 'green'},
        [8] = {title = 'Predatory Driving', class = 'Summary', id = 'S. 51A C.A.', months = 25, fine = 15000, color = 'orange', description = 'Section 51A Crimes Act - The driver of a vehicle who, while in pursuit of or travelling near another vehicle engages in a course of conduct that causes or threatens an impact involving the other vehicle, and intends by that course of conduct to cause a person in the other vehicle actual bodily harm'},
        [9] = {title = 'Speed in Manner Dangerous', class = 'Summary', id = 'S. 117 R.T.A.', months = 15, fine = 3000, color = 'green'},
        [10] = {title = 'Failure of driver to disclose identity', class = 'Summary', id = 'S. 15 LEPRA', months = 15, fine = 2000, color = 'green'},
        [11] = {title = 'Failure of owner to disclose identity', class = 'Summary', id = 'S. 17 LEPRA', months = 15, fine = 2000, color = 'green', description = 'Section 17 Law Enforcement Powers and Responsibilities Act (NSW) - An owner of a vehicle who is required in accordance with section 14 by a police officer to disclose the identity of the driver of, or a passenger in or on, the vehicle must (unless the owner has a reasonable excuse for not doing so), disclose the identity of any person the owner knows or has reason to suspect was the driver or a passenger, or if the owner does not know the full and correct identity of the person--disclose such information about the persons identity (such as any alias used by the person or the general location of his or her residential address) as is known to the owner.'},
        [12] = {title = 'False information about identity of driver or passengers', class = 'Summary', id = 'S. 18 LEPRA', months = 15, fine = 2000, color = 'green'},
        [13] = {title = 'Fail/refuse to stop vehicle when directed', class = 'Summary', id = 'S. 39 LEPRA', months = 15, fine = 5000, color = 'green'},
        [14] = {title = 'Fail/refuse to comply with lawful direction (Traffic)', class = 'Summary', id = 'S. 39 LEPRA', months = 15, fine = 5000, color = 'green'},
        [15] = {title = 'Not give particulars to other driver (Crashes)', class = 'Summary', id = 'R.R. Rule 287', months = 15, fine = 5000, color = 'green'},
        [16] = {title = 'Not give particulars to injured person (Crashes)', class = 'Summary', id = 'R.R. Rule 287', months = 15, fine = 5000, color = 'green'},
        [17] = {title = 'Not give particulars to owner of damaged property (Crashes)', class = 'Summary', id = 'R.R. Rule 287', months = 15, fine = 5000, color = 'green'},
    },
    --Traffic - Defects & Licensing
    [10] = {
        [1] = {title = 'Driving without appropriate licence', class = 'Summary', id = 'S. 53 R.T.A.', months = 15, fine = 5000, color = 'green'},
        [2] = {title = 'Driving whilst suspended/disqualified', class = 'Summary', id = 'S. 54 R.T.A.', months = 15, fine = 5000, color = 'green'},
        [3] = {title = 'Make drivers licence application whilst suspended/disqualified', class = 'Summary', id = 'S. 54 R.T.A.', months = 15, fine = 5000, color = 'green'},
        [4] = {title = 'Driving an unregistered vehicle', class = 'Summary', id = 'S. 68 R.T.A.', months = 0, fine = 2000, color = 'green'},
        [5] = {title = 'Use vehicle not complying with roadworthy standards', class = 'Summary', id = 'RT (VR) Reg 2007', months = 0, fine = 2000, color = 'green'},
        [6] = {title = 'Start/Drive vehicle causing unnecessary noise/smoke', class = 'Summary', id = 'R.R. 2014 Rule 291', months = 0, fine = 2000, color = 'green'},
        [7] = {title = 'Use vehicle in breach of minor defect notice', class = 'Summary', id = 'RT (VR) Reg 2017 Cl 128(2)', months = 0, fine = 2000, color = 'green'},
        [8] = {title = 'Use vehicle in breach of major defect notice', class = 'Summary', id = 'RT (VR) Reg 2017 Cl 128(2)', months = 0, fine = 3500, color = 'green'},
        [9] = {title = 'Use heavy vehicle in breach of minor defect notice', class = 'Summary', id = 'HVNL S. 529', months = 0, fine = 5000, color = 'green'},
        [10] = {title = 'Use heavy vehicle in breach of major defect notice', class = 'Summary', id = 'HVNL S. 529', months = 0, fine = 5000, color = 'green'},
    },
    --Traffic - Signs & Lights
    [11] = {
        [1] = {title = 'Proceed through red traffic light', class = 'Summary', id = 'R.R. 2014 Rule 59(1)', months = 0, fine = 2500, color = 'green'},
        [2] = {title = 'Not stop before traffic lights at yellow light', class = 'Summary', id = 'R.R. Rule 57 (1)(b)', months = 0, fine = 2500, color = 'green'},
        [3] = {title = 'Not stop at/before stop line/stop sign', class = 'Summary', id = 'R.R. Rule 68 (1)', months = 0, fine = 2000, color = 'green'},
        [4] = {title = 'Not give way to vehicle (give way sign/line)', class = 'Summary', id = 'R.R. Rule 69 (1)', months = 0, fine = 2000, color = 'green'},
        [5] = {title = 'Not give way to pedestrian on pedestrian crossing', class = 'Summary', id = 'R.R. Rule 81 (2)', months = 0, fine = 2500, color = 'green'},
        [6] = {title = 'Drive contrary to direction of traffic lane arrow', class = 'Summary', id = 'R.R. Rule 92 (1)', months = 0, fine = 1000, color = 'green'},
        [7] = {title = 'Pass / Overtake Vehicle contrary to no overtaking or passing sign', class = 'Summary', id = 'R.R. Rule 93 (1)', months = 0, fine = 1000, color = 'green'},
        [8] = {title = 'Drive in emergency stopping lane', class = 'Summary', id = 'R.R. Rule 95 (1)', months = 0, fine = 1000, color = 'green'},
        [9] = {title = 'Disobey no entry sign', class = 'Summary', id = 'R.R. Rule 100', months = 0, fine = 1000, color = 'green'},
        [10] = {title = 'Disobey one-way sign', class = 'Summary', id = 'R.R. Rule 98(1)', months = 0, fine = 1000, color = 'green'},
        [11] = {title = 'Unreasonably obstruct driver/pedestrian', class = 'Summary', id = 'R.R. Rule 125(1)', months = 0, fine = 1000, color = 'green'},
        [12] = {title = 'Drive behind other vehicle too closely to stop safely', class = 'Summary', id = 'R.R. Rule 126', months = 0, fine = 2500, color = 'green'},
        [13] = {title = 'Not keep right of dividing line', class = 'Summary', id = 'R.R. Rule 132(2)', months = 0, fine = 2000, color = 'green'},
        [14] = {title = 'Drive on dividing strip', class = 'Summary', id = 'R.R. Rule 137(1)', months = 0, fine = 1000, color = 'green'},
        [15] = {title = 'Illegal U-Turn', class = 'Summary', id = 'R.R. Rule 37-42', months = 0, fine = 800, color = 'green'},

    },
    -- Traffic - Vehicle Operation
    [12] = {
        [1] = {title = 'Overtake vehicle when unsafe', class = 'Summary', id = 'R.R. Rule 140', months = 0, fine = 2000, color = 'green'},
        [2] = {title = 'Cut in front of vehicle after overtaking', class = 'Summary', id = 'R.R. Rule 144(b)', months = 0, fine = 2000, color = 'green'},
        [3] = {title = 'Ride motorcycle more than 2 abreast on road or in marked lane', class = 'Summary', id = 'R.R. Rule 151', months = 0, fine = 1000, color = 'green'},
        [4] = {title = 'Leave engine on when vehicle unattended', class = 'Summary', id = 'R.R. Rule 213(3)', months = 0, fine = 800, color = 'green'},
        [5] = {title = 'Not remove ignitiion key (vehicle unattended)', class = 'Summary', id = 'R.R. Rule 213(4)', months = 0, fine = 800, color = 'green'},
        [6] = {title = 'Not secure windows/lock doors (vehicle unattended)', class = 'Summary', id = 'R.R. Rule 213(4)', months = 0, fine = 800, color = 'green'},
        [7] = {title = 'Not secure windows/lock doors (vehicle unattended)', class = 'Summary', id = 'R.R. Rule 213(5)', months = 0, fine = 800, color = 'green'},
        [8] = {title = 'Drive during period of darkness without prescribed lights', class = 'Summary', id = 'R.R. Rule 215-1(1)', months = 0, fine = 800, color = 'green'},
        [9] = {title = 'Use high beam on oncoming vehicle', class = 'Summary', id = 'R.R. Rule 218(1)', months = 0, fine = 800, color = 'green'},
        [10] = {title = 'Use horn unnecessarily', class = 'Summary', id = 'R.R. Rule 224', months = 0, fine = 2000, color = 'green'},
        [11] = {title = 'Driver/rider/passenger use device to make sound like a siren', class = 'Summary', id = 'R.R. Rule 224-1', months = 0, fine = 2000, color = 'green'},
        [12] = {title = 'Driver not wearing seatbelt', class = 'Summary', id = 'R.R. Rule 264', months = 0, fine = 2000, color = 'green'},
        [13] = {title = 'Passenger not wear seatbelt properly', class = 'Summary', id = 'R.R. Rule 267', months = 0, fine = 2000, color = 'green'},
        [14] = {title = 'Travel in/on vehicle in part not for passengers/goods', class = 'Summary', id = 'R.R. Rule 268', months = 0, fine = 2000, color = 'green'},
        [15] = {title = 'Travel in/on boot of motor vehicle', class = 'Summary', id = 'R.R. Rule 268-1', months = 0, fine = 2000, color = 'green'},
        [16] = {title = 'Drive motor vehicle with persons in or on boot', class = 'Summary', id = 'R.R. Rule 268-2', months = 0, fine = 2000, color = 'green'},
        [17] = {title = 'Ride motorcycle with no helmet', class = 'Summary', id = 'R.R. Rule 270(1)(a)', months = 0, fine = 2000, color = 'green'},
        [18] = {title = 'Ride motorcycle with one unhelmeted passenger', class = 'Summary', id = 'R.R. Rule 270(1)(b)', months = 0, fine = 2000, color = 'green'},
        [19] = {title = 'Motorcycle passenger not wearing helmet', class = 'Summary', id = 'R.R. Rule 270(2)', months = 0, fine = 2000, color = 'green'},
        [20] = {title = 'Drive on path', class = 'Summary', id = 'R.R. Rule 287', months = 0, fine = 2000, color = 'green'},
        [21] = {title = 'Drive on nature strip', class = 'Summary', id = 'R.R. Rule 289', months = 0, fine = 2000, color = 'green'},
        [22] = {title = 'Drive on traffic island', class = 'Summary', id = 'R.R. Rule 289', months = 0, fine = 2000, color = 'green'},
        [23] = {title = 'Drive/tow vehicle with unsecured load', class = 'Summary', id = 'R.R. Rule 292(a)', months = 0, fine = 2500, color = 'green'},
        [24] = {title = 'Not reverse safely', class = 'Summary', id = 'R.R. Rule 296(1)', months = 0, fine = 192, color = 'green'},
        [25] = {title = 'Drive without proper control of vehicle', class = 'Summary', id = 'R.R. Rule 297(1)', months = 0, fine = 2500, color = 'green'},
        [26] = {title = 'Drive motor vehicle with person or animal in lap', class = 'Summary', id = 'R.R. Rule 297(1A)', months = 0, fine = 2500, color = 'green'},
        [27] = {title = 'Drive using mobile phone when not permitted', class = 'Summary', id = 'R.R. Rule 300', months = 0, fine = 2000, color = 'green'},
        [28] = {title = 'Driver consume alcohol while driving', class = 'Summary', id = 'R.R. Rule 298', months = 0, fine = 2000, color = 'green'},
        [29] = {title = 'Driver motor vehicle not carry licence', class = 'Summary', id = 'R.R. Rule 300-5', months = 0, fine = 2000, color = 'green'},
        [30] = {title = 'Not obey direction of police/authorised person', class = 'Summary', id = 'R.R. Rule 304(1)', months = 0, fine = 2000, color = 'green'},
        [31] = {title = 'Burnout', class = 'Summary', id = 'S. 116 R.T.A.', months = 0, fine = 3000, color = 'green'},
        [32] = {title = 'Use vehicle without correctly fixed/displayed number plate', class = 'Summary', id = 'R.R. (VR) Cl 60', months = 0, fine = 2500, color = 'green'},
        [33] = {title = 'Use vehicle displaying misleading plate', class = 'Summary', id = 'R.R. (VR) Cl 129 (3)(b)', months = 0, fine = 2500, color = 'green'},
        [34] = {title = 'Use vehicle with sound system emitting offensive noise', class = 'Summary', id = 'PE(NC) Reg 2017 Cl 33(1)', months = 0, fine = 300, color = 'green'},
        [35] = {title = 'Organise, promote, or take part in street race', class = 'Summary', id = 'S. 115 R.T.A.', months = 15, fine = 10000, color = 'green'},
    },

    --Speeding
    [13] = {

        [1] = {title = 'Speeding over 10kmph', class = 'Summary', id = 'R.R. Rule 20', months = 0, fine = 1000, color = 'green'},
        [2] = {title = 'Speeding over 20kmph', class = 'Summary', id = 'R.R. Rule 20', months = 0, fine = 2000, color = 'green'},
        [3] = {title = 'Speeding over 30kmph', class = 'Summary', id = 'R.R. Rule 20', months = 0, fine = 3000, color = 'green'},
        [4] = {title = 'Speeding over 45kmph', class = 'Summary', id = 'R.R. Rule 20', months = 0, fine = 5000, color = 'green'},
        [5] = {title = 'Speeding over 100kmph', class = 'Summary', id = 'R.R. Rule 20', months = 0, fine = 6000, color = 'green'},
        [6] = {title = 'Speeding over 10kmph (Heavy Vehicle)', class = 'Summary', id = 'R.R. Rule 20', months = 0, fine = 1500, color = 'green'},
        [7] = {title = 'Speeding over 20kmph (Heavy Vehicle)', class = 'Summary', id = 'R.R. Rule 20', months = 0, fine = 2500, color = 'green'},
        [8] = {title = 'Speeding over 30kmph (Heavy Vehicle)', class = 'Summary', id = 'R.R. Rule 20', months = 0, fine = 3500, color = 'green'},
        [9] = {title = 'Speeding over 45kmph (Heavy Vehicle)', class = 'Summary', id = 'R.R. Rule 20', months = 0, fine = 5500, color = 'green'},
        [10] = {title = 'Speeding over 100kmph (Heavy Vehicle)', class = 'Summary', id = 'R.R. Rule 20', months = 0, fine = 6500, color = 'green'},

    },
    --Drink / Drug Driving
    [14] = {

        [1] = {title = 'Low-range drink driving (BAC 0.05 - 0.079)', class = 'Summary', id = 'S. 110 R.T.A.', months = 0, fine = 1000, color = 'green'},
        [2] = {title = 'Mid-range drink driving (BAC 0.08 - 0.149)', class = 'Summary', id = 'S. 110 R.T.A.', months = 12, fine = 3000, color = 'green'},
        [3] = {title = 'High-range drink driving (BAC 0.15 or higher)', class = 'Summary', id = 'S. 110 R.T.A.', months = 24, fine = 5000, color = 'green'},
        [4] = {title = 'Drive with presence of illicit drugs in system', class = 'Summary', id = 'S. 111 R.T.A.', months = 0, fine = 5000, color = 'green'},
        [5] = {title = 'Driving under the influence', class = 'Summary', id = 'S. 112 R.T.A.', months = 18, fine = 5000, color = 'green'},


    },
}

Config.AllowedJobs = {}
for index, value in pairs(Config.PoliceJobs) do
    Config.AllowedJobs[index] = value
end
for index, value in pairs(Config.AmbulanceJobs) do
    Config.AllowedJobs[index] = value
end
for index, value in pairs(Config.DojJobs) do
    Config.AllowedJobs[index] = value
end

Config.ColorNames = {
    [0] = "Metallic Black",
    [1] = "Metallic Graphite Black",
    [2] = "Metallic Black Steel",
    [3] = "Metallic Dark Silver",
    [4] = "Metallic Silver",
    [5] = "Metallic Blue Silver",
    [6] = "Metallic Steel Gray",
    [7] = "Metallic Shadow Silver",
    [8] = "Metallic Stone Silver",
    [9] = "Metallic Midnight Silver",
    [10] = "Metallic Gun Metal",
    [11] = "Metallic Anthracite Grey",
    [12] = "Matte Black",
    [13] = "Matte Gray",
    [14] = "Matte Light Grey",
    [15] = "Util Black",
    [16] = "Util Black Poly",
    [17] = "Util Dark silver",
    [18] = "Util Silver",
    [19] = "Util Gun Metal",
    [20] = "Util Shadow Silver",
    [21] = "Worn Black",
    [22] = "Worn Graphite",
    [23] = "Worn Silver Grey",
    [24] = "Worn Silver",
    [25] = "Worn Blue Silver",
    [26] = "Worn Shadow Silver",
    [27] = "Metallic Red",
    [28] = "Metallic Torino Red",
    [29] = "Metallic Formula Red",
    [30] = "Metallic Blaze Red",
    [31] = "Metallic Graceful Red",
    [32] = "Metallic Garnet Red",
    [33] = "Metallic Desert Red",
    [34] = "Metallic Cabernet Red",
    [35] = "Metallic Candy Red",
    [36] = "Metallic Sunrise Orange",
    [37] = "Metallic Classic Gold",
    [38] = "Metallic Orange",
    [39] = "Matte Red",
    [40] = "Matte Dark Red",
    [41] = "Matte Orange",
    [42] = "Matte Yellow",
    [43] = "Util Red",
    [44] = "Util Bright Red",
    [45] = "Util Garnet Red",
    [46] = "Worn Red",
    [47] = "Worn Golden Red",
    [48] = "Worn Dark Red",
    [49] = "Metallic Dark Green",
    [50] = "Metallic Racing Green",
    [51] = "Metallic Sea Green",
    [52] = "Metallic Olive Green",
    [53] = "Metallic Green",
    [54] = "Metallic Gasoline Blue Green",
    [55] = "Matte Lime Green",
    [56] = "Util Dark Green",
    [57] = "Util Green",
    [58] = "Worn Dark Green",
    [59] = "Worn Green",
    [60] = "Worn Sea Wash",
    [61] = "Metallic Midnight Blue",
    [62] = "Metallic Dark Blue",
    [63] = "Metallic Saxony Blue",
    [64] = "Metallic Blue",
    [65] = "Metallic Mariner Blue",
    [66] = "Metallic Harbor Blue",
    [67] = "Metallic Diamond Blue",
    [68] = "Metallic Surf Blue",
    [69] = "Metallic Nautical Blue",
    [70] = "Metallic Bright Blue",
    [71] = "Metallic Purple Blue",
    [72] = "Metallic Spinnaker Blue",
    [73] = "Metallic Ultra Blue",
    [74] = "Metallic Bright Blue",
    [75] = "Util Dark Blue",
    [76] = "Util Midnight Blue",
    [77] = "Util Blue",
    [78] = "Util Sea Foam Blue",
    [79] = "Uil Lightning blue",
    [80] = "Util Maui Blue Poly",
    [81] = "Util Bright Blue",
    [82] = "Matte Dark Blue",
    [83] = "Matte Blue",
    [84] = "Matte Midnight Blue",
    [85] = "Worn Dark blue",
    [86] = "Worn Blue",
    [87] = "Worn Light blue",
    [88] = "Metallic Taxi Yellow",
    [89] = "Metallic Race Yellow",
    [90] = "Metallic Bronze",
    [91] = "Metallic Yellow Bird",
    [92] = "Metallic Lime",
    [93] = "Metallic Champagne",
    [94] = "Metallic Pueblo Beige",
    [95] = "Metallic Dark Ivory",
    [96] = "Metallic Choco Brown",
    [97] = "Metallic Golden Brown",
    [98] = "Metallic Light Brown",
    [99] = "Metallic Straw Beige",
    [100] = "Metallic Moss Brown",
    [101] = "Metallic Biston Brown",
    [102] = "Metallic Beechwood",
    [103] = "Metallic Dark Beechwood",
    [104] = "Metallic Choco Orange",
    [105] = "Metallic Beach Sand",
    [106] = "Metallic Sun Bleeched Sand",
    [107] = "Metallic Cream",
    [108] = "Util Brown",
    [109] = "Util Medium Brown",
    [110] = "Util Light Brown",
    [111] = "Metallic White",
    [112] = "Metallic Frost White",
    [113] = "Worn Honey Beige",
    [114] = "Worn Brown",
    [115] = "Worn Dark Brown",
    [116] = "Worn straw beige",
    [117] = "Brushed Steel",
    [118] = "Brushed Black steel",
    [119] = "Brushed Aluminium",
    [120] = "Chrome",
    [121] = "Worn Off White",
    [122] = "Util Off White",
    [123] = "Worn Orange",
    [124] = "Worn Light Orange",
    [125] = "Metallic Securicor Green",
    [126] = "Worn Taxi Yellow",
    [127] = "police car blue",
    [128] = "Matte Green",
    [129] = "Matte Brown",
    [130] = "Worn Orange",
    [131] = "Matte White",
    [132] = "Worn White",
    [133] = "Worn Olive Army Green",
    [134] = "Pure White",
    [135] = "Hot Pink",
    [136] = "Salmon pink",
    [137] = "Metallic Vermillion Pink",
    [138] = "Orange",
    [139] = "Green",
    [140] = "Blue",
    [141] = "Mettalic Black Blue",
    [142] = "Metallic Black Purple",
    [143] = "Metallic Black Red",
    [144] = "Hunter Green",
    [145] = "Metallic Purple",
    [146] = "Metaillic V Dark Blue",
    [147] = "MODSHOP BLACK1",
    [148] = "Matte Purple",
    [149] = "Matte Dark Purple",
    [150] = "Metallic Lava Red",
    [151] = "Matte Forest Green",
    [152] = "Matte Olive Drab",
    [153] = "Matte Desert Brown",
    [154] = "Matte Desert Tan",
    [155] = "Matte Foilage Green",
    [156] = "DEFAULT ALLOY COLOR",
    [157] = "Epsilon Blue",
    [158] = "Unknown",
}

Config.ColorInformation = {
    [0] = "black",
    [1] = "black",
    [2] = "black",
    [3] = "darksilver",
    [4] = "silver",
    [5] = "bluesilver",
    [6] = "silver",
    [7] = "darksilver",
    [8] = "silver",
    [9] = "bluesilver",
    [10] = "darksilver",
    [11] = "darksilver",
    [12] = "matteblack",
    [13] = "gray",
    [14] = "lightgray",
    [15] = "black",
    [16] = "black",
    [17] = "darksilver",
    [18] = "silver",
    [19] = "utilgunmetal",
    [20] = "silver",
    [21] = "black",
    [22] = "black",
    [23] = "darksilver",
    [24] = "silver",
    [25] = "bluesilver",
    [26] = "darksilver",
    [27] = "red",
    [28] = "torinored",
    [29] = "formulared",
    [30] = "blazered",
    [31] = "gracefulred",
    [32] = "garnetred",
    [33] = "desertred",
    [34] = "cabernetred",
    [35] = "candyred",
    [36] = "orange",
    [37] = "gold",
    [38] = "orange",
    [39] = "red",
    [40] = "mattedarkred",
    [41] = "orange",
    [42] = "matteyellow",
    [43] = "red",
    [44] = "brightred",
    [45] = "garnetred",
    [46] = "red",
    [47] = "red",
    [48] = "darkred",
    [49] = "darkgreen",
    [50] = "racingreen",
    [51] = "seagreen",
    [52] = "olivegreen",
    [53] = "green",
    [54] = "gasolinebluegreen",
    [55] = "mattelimegreen",
    [56] = "darkgreen",
    [57] = "green",
    [58] = "darkgreen",
    [59] = "green",
    [60] = "seawash",
    [61] = "midnightblue",
    [62] = "darkblue",
    [63] = "saxonyblue",
    [64] = "blue",
    [65] = "blue",
    [66] = "blue",
    [67] = "diamondblue",
    [68] = "blue",
    [69] = "blue",
    [70] = "brightblue",
    [71] = "purpleblue",
    [72] = "blue",
    [73] = "ultrablue",
    [74] = "brightblue",
    [75] = "darkblue",
    [76] = "midnightblue",
    [77] = "blue",
    [78] = "blue",
    [79] = "lightningblue",
    [80] = "blue",
    [81] = "brightblue",
    [82] = "mattedarkblue",
    [83] = "matteblue",
    [84] = "matteblue",
    [85] = "darkblue",
    [86] = "blue",
    [87] = "lightningblue",
    [88] = "yellow",
    [89] = "yellow",
    [90] = "bronze",
    [91] = "yellow",
    [92] = "lime",
    [93] = "champagne",
    [94] = "beige",
    [95] = "darkivory",
    [96] = "brown",
    [97] = "brown",
    [98] = "lightbrown",
    [99] = "beige",
    [100] = "brown",
    [101] = "brown",
    [102] = "beechwood",
    [103] = "beechwood",
    [104] = "chocoorange",
    [105] = "yellow",
    [106] = "yellow",
    [107] = "cream",
    [108] = "brown",
    [109] = "brown",
    [110] = "brown",
    [111] = "white",
    [112] = "white",
    [113] = "beige",
    [114] = "brown",
    [115] = "brown",
    [116] = "beige",
    [117] = "steel",
    [118] = "blacksteel",
    [119] = "aluminium",
    [120] = "chrome",
    [121] = "wornwhite",
    [122] = "offwhite",
    [123] = "orange",
    [124] = "lightorange",
    [125] = "green",
    [126] = "yellow",
    [127] = "blue",
    [128] = "green",
    [129] = "brown",
    [130] = "orange",
    [131] = "white",
    [132] = "white",
    [133] = "darkgreen",
    [134] = "white",
    [135] = "pink",
    [136] = "pink",
    [137] = "pink",
    [138] = "orange",
    [139] = "green",
    [140] = "blue",
    [141] = "blackblue",
    [142] = "blackpurple",
    [143] = "blackred",
    [144] = "darkgreen",
    [145] = "purple",
    [146] = "darkblue",
    [147] = "black",
    [148] = "purple",
    [149] = "darkpurple",
    [150] = "red",
    [151] = "darkgreen",
    [152] = "olivedrab",
    [153] = "brown",
    [154] = "tan",
    [155] = "green",
    [156] = "silver",
    [157] = "blue",
    [158] = "black",
}

Config.ClassList = {
    [0] = "Compact",
    [1] = "Sedan",
    [2] = "SUV",
    [3] = "Coupe",
    [4] = "Muscle",
    [5] = "Sport Classic",
    [6] = "Sport",
    [7] = "Super",
    [8] = "Motorbike",
    [9] = "Off-Road",
    [10] = "Industrial",
    [11] = "Utility",
    [12] = "Van",
    [13] = "Bike",
    [14] = "Boat",
    [15] = "Helicopter",
    [16] = "Plane",
    [17] = "Service",
    [18] = "Emergency",
    [19] = "Military",
    [20] = "Commercial",
    [21] = "Train"
}

function GetJobType(job)
	if Config.PoliceJobs[job] then
		return 'police'
	elseif Config.AmbulanceJobs[job] then
		return 'ambulance'
	elseif Config.DojJobs[job] then
		return 'doj'
	else
		return nil
	end
end
